### ISSUE TITLE
Class goals

### ISSUE THREAD

**Issue by hubyeti** [NileshArnaiya/github-for-developers-7#1]
Please tell us one thing you would like to learn in today's class!

**Comment by NileshArnaiya** [comment]
![240813_221995264497172_6027781_o](https://cloud.githubusercontent.com/assets/10388565/11307806/7440d046-8fe0-11e5-9d46-d417c7d889d9.jpg)
 <h1>git commands</h1>
ForMySelf
<a href="http://www.nilesharnaiya.site50.net"> Visit my website </a>
